app/models/categoria.py
from app import db

class Categoria(db.Model):
    __tablename__ = 'categoria'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(100), nullable=True)
    genero = db.Column(db.String(10), nullable=False)


    productos = db.relationship('Producto', back_populates='categoria')

app/routes/categoria_routes.py
from flask import Blueprint, request, redirect, url_for, render_template
from app import db
from app.models.categoria import Categoria

bp = Blueprint('categoria', __name__)

@bp.route('/categoria', methods=['GET'])
def index():
    data = Categoria.query.all()
    return render_template('categoria/index.html', data=data)

@bp.route('/categoria/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre = request.form.get('nombre')
        genero = request.form['genero']

        if not nombre:
            # Aquí puedes agregar manejo de errores
            return render_template('categoria/add.html', error='El nombre es requerido.')
        
        if not genero:
            # Aquí puedes agregar manejo de errores
            return render_template('categoria/add.html', error='El genero es requerido.')

        newCategory = Categoria(nombre=nombre, genero=genero)
        db.session.add(newCategory)
        db.session.commit()
        return redirect(url_for('categoria.index'))
    return render_template('categoria/add.html')

@bp.route('/categoria/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    categoria = Categoria.query.get_or_404(id)
    if request.method == 'POST':
        nombre = request.form.get('nombre')

        if not nombre:
            return render_template('categoria/edit.html', categoria=categoria, error='El nombre es requerido.')

        categoria.nombre = nombre
        db.session.commit()
        return redirect(url_for('categoria.index'))
    return render_template('categoria/edit.html', categoria=categoria)

@bp.route('/categoria/delete/<int:id>')
def delete(id):
    category = Categoria.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('categoria.index'))

app/templates/categoria/add.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Añadir Categoría</title>
</head>
<body>
    <h1>Añadir Categoría</h1>
    {% if error %}
    <p style="color:red;">{{ error }}</p>
    {% endif %}
    <form action="{{ url_for('categoria.add') }}" method="POST">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>

        <label for="genero">Género:</label>
        <select name="genero" id="genero" required>
            <option value="Hombre">Hombre</option>
            <option value="Mujer">Mujer</option>
            <option value="Unisex">Unisex</option>
        </select>


        <button type="submit">Añadir Categoría</button>
    </form>
</body>
</html>

app/templates/categoria/edit.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Categoría</title>
</head>
<body>
    <h1>Editar Categoría</h1>
    {% if error %}
    <p style="color:red;">{{ error }}</p>
    {% endif %}
    <form action="{{ url_for('categoria.edit', id=categoria.id) }}" method="POST">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ categoria.nombre }}" required>
        <button type="submit">Actualizar Categoría</button>
    </form>
</body>
</html>

app/templates/categoria/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Categorías</title>
</head>
<body>
    <h1>Lista de Categorías</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre de la Categoría</th>
            <th>Acciones</th>
        </tr>  
        {% for categoria in data %}
            <tr>
                <td>{{ categoria.id }}</td>
                <td>{{ categoria.nombre }}</td>
                <td>
                    <a href="{{ url_for('categoria.edit', id=categoria.id) }}">Editar</a>
                    <a href="{{ url_for('categoria.delete', id=categoria.id) }}">Eliminar</a> 
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('categoria.add') }}">Agregar Categoría</a>
    <a href="{{ url_for('producto.index') }}">Ir a Productos</a>
</body>
</html>